Controllers/AdoptionController.cs
using Adopta_O_Emotie_Virtuala.Data;
using Adopta_O_Emotie_Virtuala.Models.DomainModels;
using Adopta_O_Emotie_Virtuala.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Adopta_O_Emotie_Virtuala.Controllers
{
    public class AdoptionController : Controller
    {
        private readonly MVCDbContext mVCDbContext;
        public AdoptionController(MVCDbContext mVCDbContext)
        {
            this.mVCDbContext = mVCDbContext;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var adoptions = await mVCDbContext.Adoptions.ToListAsync();
            return View(adoptions);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddAdoptionViewModel addAdoptionRequest)
        {
            var adoption = new Adoption()
            {
                ID_Adoption = Guid.NewGuid(),
                ID_Animal = addAdoptionRequest.ID_Animal,
                ID_Parent = addAdoptionRequest.ID_Parent,
                DateOfAdoption = addAdoptionRequest.DateOfAdoption,
                Status=addAdoptionRequest.Status
            };
            await mVCDbContext.Adoptions.AddAsync(adoption);
            await mVCDbContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> View(Guid id)
        {
            var adoption = await mVCDbContext.Adoptions.FirstOrDefaultAsync(x => x.ID_Adoption == id);

            if (adoption != null)
            {
                var viewModel = new UpdateAdoptionViewModel()
                {
                    ID_Adoption = adoption.ID_Adoption, ID_Animal = adoption.ID_Animal, ID_Parent= adoption.ID_Parent, DateOfAdoption= adoption.DateOfAdoption, Status=adoption.Status
                };
                return await Task.Run(() => View("View", viewModel));
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> View(UpdateAdoptionViewModel model)
        {
            var adoption = await mVCDbContext.Adoptions.FindAsync(model.ID_Adoption);
            if (adoption != null)
            {
                adoption.ID_Adoption = model.ID_Adoption;
                adoption.ID_Animal = model.ID_Animal;
                adoption.ID_Parent = model.ID_Parent;
                adoption.DateOfAdoption = model.DateOfAdoption;
                adoption.Status = model.Status;


                await mVCDbContext.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(UpdateAdoptionViewModel model)
        {
            var adoption = await mVCDbContext.Adoptions.FindAsync(model.ID_Adoption);
            if (adoption != null)
            {
                mVCDbContext.Adoptions.Remove(adoption);
                await mVCDbContext.SaveChangesAsync();

                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
    }
}

Controllers/ParentsController.cs
using Adopta_O_Emotie_Virtuala.Data;
using Adopta_O_Emotie_Virtuala.Models.DomainModels;
using Adopta_O_Emotie_Virtuala.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Adopta_O_Emotie_Virtuala.Controllers
{
    public class ParentsController : Controller
    {
        private readonly MVCDbContext mVCDbContext;
        public ParentsController(MVCDbContext mVCDbContext)
        {
            this.mVCDbContext = mVCDbContext;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var parents = await mVCDbContext.Foster_Parents.ToListAsync();
            return View(parents);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

       [HttpPost]
        public async Task<IActionResult> Add(AddParentViewModel addParentRequest)
        {
           
            var parent = new Foster_parents()
            {
                ID_Parent = Guid.NewGuid(),
                ID_User = addParentRequest.ID_User,
                ExperienceWithAnimals = addParentRequest.ExperienceWithAnimals,
                Prefrences = addParentRequest.Prefrences
            };
            await mVCDbContext.Foster_Parents.AddAsync(parent);
            await mVCDbContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> View(Guid id)
        {
            var parent = await mVCDbContext.Foster_Parents.FirstOrDefaultAsync(x => x.ID_Parent == id);

            if (parent != null)
            {
                var viewModel = new UpdateParentsViewModel()
                {
                    ID_Parent = parent.ID_Parent,
                    ID_User = parent.ID_User,
                    ExperienceWithAnimals = parent.ExperienceWithAnimals,
                    Prefrences = parent.Prefrences
                };
                return await Task.Run(() => View("View", viewModel));
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> View(UpdateParentsViewModel model)
        {
            var parent = await mVCDbContext.Foster_Parents.FindAsync(model.ID_Parent);
            if (parent != null)
            {
                parent.ID_Parent = model.ID_Parent;
                parent.ID_User = model.ID_User;
                parent.ExperienceWithAnimals = model.ExperienceWithAnimals;
                parent.Prefrences = model.Prefrences;


                await mVCDbContext.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(UpdateParentsViewModel model)
        {
            var parent = await mVCDbContext.Foster_Parents.FindAsync(model.ID_Parent);
            if (parent != null)
            {
                mVCDbContext.Foster_Parents.Remove(parent);
                await mVCDbContext.SaveChangesAsync();

                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
    }
}

Controllers/UsersController.cs
using Adopta_O_Emotie_Virtuala.Data;
using Adopta_O_Emotie_Virtuala.Models;
using Adopta_O_Emotie_Virtuala.Models.DomainModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Net;
using System.Numerics;

namespace Adopta_O_Emotie_Virtuala.Controllers
{
    public class UsersController : Controller
    {
        private readonly MVCDbContext mVCDbContext;
        public UsersController(MVCDbContext mVCDbContext) { 
        this.mVCDbContext = mVCDbContext;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
           var users = await mVCDbContext.Users.ToListAsync();
            return View(users);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddUserViewModel addUserRequest)
        { 
            var user = new User()
            {
                Id = Guid.NewGuid(),
                Name = addUserRequest.Name,
                Email= addUserRequest.Email,
                Phone= addUserRequest.Phone,
                Address= addUserRequest.Address,
                DateOfBirth= addUserRequest.DateOfBirth,
                Password= addUserRequest.Password
            };
            await mVCDbContext.Users.AddAsync(user);
            await mVCDbContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> View(Guid id)
        {
            var user = await mVCDbContext.Users.FirstOrDefaultAsync(x => x.Id == id);

            if (user != null)
            {
                var viewModel = new UpdateUsersViewModel()
                {
                    Id = user.Id,
                    Name = user.Name,
                    Email = user.Email,
                    Phone = user.Phone,
                    Address = user.Address,
                    DateOfBirth = user.DateOfBirth,
                    Password = user.Password

                };
                return await Task.Run(() => View("View", viewModel));
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> View(UpdateUsersViewModel model)
        {
            var user = await mVCDbContext.Users.FindAsync(model.Id);
            if (user != null)
            {
                user.Name = model.Name;
                user.Email = model.Email;
                user.Phone = model.Phone;
                user.Address = model.Address;
                user.DateOfBirth = model.DateOfBirth;
                user.Password = model.Password;

                await mVCDbContext.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(UpdateUsersViewModel model)
        {
            var user = await mVCDbContext.Users.FindAsync(model.Id);
            if (user != null)
            {
                mVCDbContext.Users.Remove(user);
                await mVCDbContext.SaveChangesAsync();

                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Adopta_O_Emotie_Virtuala</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Adopta_O_Emotie_Virtuala.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Adopta_O_Emotie_Virtuala</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Animals" asp-action="Index">Animals</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Animals" asp-action="Add">Add Animals</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Add">Create user account</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Adoption" asp-action="Add">Add information about adoptions</a>
                        </li>
                         <li class="nav-item">
                           <a class="nav-link text-dark" asp-area="" asp-controller="Adoption" asp-action="Index">Info Adoptions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Parents" asp-action="Add">Add information about foster parents</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Parents" asp-action="Index">Info foster parents</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Adopta_O_Emotie_Virtuala - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>